# Generated by Django 4.1.4 on 2022-12-28 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familiares', '0002_alter_familiares_apellido_alter_familiares_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='familiares',
            name='pariente',
            field=models.CharField(default='Hermano', max_length=100),
        ),
    ]
